server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: minha-api

  # ===============================
  # DATASOURCE - POSTGRES
  # ===============================
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: false
  # ===============================
  # FLYWAY
  # ===============================
  flyway:
    enabled: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS}
            required: true
# ===============================
# JWT
# ===============================
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

auth:
  email-verification-expiration: ${AUTH_EMAIL_VERIFICATION_EXPIRATION}
  password-reset-expiration: ${AUTH_PASSWORD_RESET_EXPIRATION}

app:
  frontend:
    url: ${APP_FRONTEND_URL}

# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    mail:
      enabled: false

cookie:
  secure: ${COOKIE_SECURE:true}
  same-site: ${SAME_SITE_SECURE:None}