server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: minha-api

  # ===============================
  # DATASOURCE - POSTGRES
  # ===============================
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  # ===============================
  # FLYWAY
  # ===============================
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    postgresql:
      transactional-lock: false

# ===============================
# JWT
# ===============================
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# ===============================
# LOGGING
# ===============================
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
cookie:
  secure: ${COOKIE_SECURE:true}
  same-site: ${SAME_SITE_SECURE:None}